// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJ7a-_28eB_PtnVV4rLX_oleYkKip09k',
    appId: '1:337236128245:web:8801462b0d8d4085b1b0bc',
    messagingSenderId: '337236128245',
    projectId: 'chappo-e5eee',
    authDomain: 'chappo-e5eee.firebaseapp.com',
    storageBucket: 'chappo-e5eee.firebasestorage.app',
    measurementId: 'G-N82G6Q6LTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiDVTxB3ukWePUENrUaWSDkkmYcJxog8',
    appId: '1:337236128245:android:c0d2c54f6beb0be7b1b0bc',
    messagingSenderId: '337236128245',
    projectId: 'chappo-e5eee',
    storageBucket: 'chappo-e5eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDF-wNTrq9m6cc4u9DsAO9Z_ZF9ZfbF4',
    appId: '1:337236128245:ios:5f8da7c327943137b1b0bc',
    messagingSenderId: '337236128245',
    projectId: 'chappo-e5eee',
    storageBucket: 'chappo-e5eee.firebasestorage.app',
    iosBundleId: 'com.example.newChappo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQDF-wNTrq9m6cc4u9DsAO9Z_ZF9ZfbF4',
    appId: '1:337236128245:ios:5f8da7c327943137b1b0bc',
    messagingSenderId: '337236128245',
    projectId: 'chappo-e5eee',
    storageBucket: 'chappo-e5eee.firebasestorage.app',
    iosBundleId: 'com.example.newChappo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnJ7a-_28eB_PtnVV4rLX_oleYkKip09k',
    appId: '1:337236128245:web:bf59816f7c056bf5b1b0bc',
    messagingSenderId: '337236128245',
    projectId: 'chappo-e5eee',
    authDomain: 'chappo-e5eee.firebaseapp.com',
    storageBucket: 'chappo-e5eee.firebasestorage.app',
    measurementId: 'G-QR22TD9E6G',
  );

}